export type NonEmptyWords = readonly [string, ...string[]];

export const THINKING_WORKING_WORDS = [
	"Pondering",
	"Cogitating",
	"Contemplating",
	"Deliberating",
	"Ruminating",
	"Mulling",
	"Brewing",
	"Distilling",
	"Synthesizing",
	"Weaving",
	"Parsing",
	"Mapping",
	"Tracing",
	"Sifting",
	"Noodling",
	"Tinkering",
	"Harmonizing",
	"Recalibrating",
	"Reconciling",
	"Assembling",
	"Sketching",
	"Unwinding",
	"Figuring",
	"Connecting",
	"Exploring",
	"Scrutinizing",
	"Sloubagoubliming",
	"Flibbertigibbering",
	"Wibblywobbling",
	"Gubberwocking",
	"Snorkelwhiffling",
	"Quibblenoodling",
	"Fiddlefaddling",
	"Twiddlethinking",
	"Blorplewaffling",
	"Zorblaxing",
] as const satisfies NonEmptyWords;
