# === Font ===
font-family = MonoLisa Nerd Font
font-size = 12

# === Cell Adjustments ===
adjust-cell-width = 5%
adjust-cell-height = 10%

# === Cursor Adjustments ===
adjust-cursor-height = 15%
adjust-cursor-thickness = 3
